config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  resources :users, only:[:index, :show]
  resources :products do
    resources :likes, only:[:create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
  validates_uniqueness_of  :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user
  has_one_attached :image
  validates :image, file_size: { in: 1.kilobytes..1.megabyte }, file_content_type: { allow: ['image/jpeg', 'image/png'] }

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar
  validates :avatar, file_size: { in: 1.kilobytes..1.megabyte }, file_content_type: { allow: ['image/jpeg', 'image/png'] }
  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/active_storage/direct_uploads_controller.rb
# app/controllers/active_storage/direct_uploads_controller.rb
# frozen_string_literal: true

# original: https://github.com/rails/rails/blob/master/activestorage/app/controllers/active_storage/direct_uploads_controller.rb
class ActiveStorage::DirectUploadsController <  ActiveStorage::BaseController
  ActiveStorage::Blob.unattached.find_each(&:purge_later)
  before_action :authenticate_user!, except: [:create]
  before_action :check_file_size!

  def create
    blob = ActiveStorage::Blob.create_before_direct_upload!(blob_args)
    render json: direct_upload_json(blob)
  end

  private
    def blob_args
      params.require(:blob).permit(:filename, :byte_size, :checksum, :content_type, :metadata).to_h.symbolize_keys
    end

    def direct_upload_json(blob)
      blob.as_json(root: false, methods: :signed_id).merge(direct_upload: {
        url: blob.service_url_for_direct_upload,
        headers: blob.service_headers_for_direct_upload
      })
    end

    def check_file_size!
      if blob_args[:byte_size] > 1.gigabyte
        render json: { message: 'File size must be less than 1GB.' }, status: :unprocessable_entity
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:nickname, :email, :password, :password_confirmation,:nickname, :avatar)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:nickname, :email, :password, :password_confirmation, :current_password, :avatar)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # before_action  :set_product,  only: [:create, :destroy]

  def create
    like = Like.new(user_id: current_user.id, product_id: params[:product_id])
    like.save
    redirect_to product_path(params[:product_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, product_id: params[:product_id])
    like.destroy
    redirect_to product_path(params[:product_id])
  end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(name: product_params[:name], description: product_params[:description], user_id: current_user.id, image: product_params[:image])
    if product.save
        redirect_to products_path,notice: "「#{product.name}」登録しました"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @like_count = Like.where(product_id: params[:product_id]).count
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.image.detach
    if product.update(product_params)
        redirect_to products_path,notice: "「#{product.name}」更新しました"
    else
        render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path,notice: "「#{product.name}」削除しました"
  end

  private

  def product_params
    params.require(:product).permit(:name,:description,:image)
  end

  def move_to_index
    redirect_to action: :index  unless user_signed_in?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @nickname = current_user.nickname
    @products = current_user.products.where(params[:description])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def devise_error_messages
    return "" if resource.errors.empty?
    errors_html = ""
    resource.errors.full_messages.each do |err_msg|
      errors_html += <<-EOF
        <div class="error_field alert alert-danger" role="alert">
          <p class="error_msg">#{err_msg}</p>
        </div>
      EOF
    end
    errors_html.html_safe
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html lang='ja'
  head
    title
      | SampleApp
    = csrf_meta_tags
    = csp_meta_tag
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body.h-100
    header
      nav.navbar.navbar-expand-sm.navbar-light.bg-light.sticky-top.py-5
        .container
          h1
            a href=root_path Sample_app
          button.navbar-toggler type='button' data-toggle='collapse' data-target='#menu'
            span.navbar-toggler-icon
          #menu.collapse.navbar-collapse
          #menu.collapse.navbar-collapse
            .ml-auto
              - if user_signed_in?
                .user_nav.d-flex.align-items-center
                  .user_image.mr-3
                    -if current_user.avatar.attached?
                      = image_tag current_user.avatar.variant(resize: "90x90"),class:'pt-2'
                  span.pr-5
                    = current_user.nickname
                  a href='/products/new' class='post mr-2 btn btn-primary'投稿
                  = link_to'マイページ',"/users/= current_user.id",class:'mr-2 btn btn-primary'
                  = link_to'ユーザー編集',edit_user_registration_path,class:'mr-2 btn btn-primary'
                  = link_to 'ログアウト', destroy_user_session_path, method: :delete,class: 'mr-2 btn btn-primary'
              - else
                  = link_to 'ログイン', new_user_session_path, class: 'post mr-2 btn btn-primary'
                  = link_to '新規登録', new_user_registration_path, class: 'post btn btn-primary'
    .container.py-5.my-5
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield
    footer.py-5.text-center.bg-secondary.text-light.lead My first app

app/views/likes/_like.html.slim
- if user_signed_in?
  - if product.like_user(current_user.id)
    = button_to product_like_path( product_id: product.id), method: :delete, id:'like-button',remote: true do
      i class='fas fa-heart'
      span
        = product.likes_count
  -else
    = button_to product_likes_path(product), id: 'like-button', remote: true do
      i class='fal fa-heart'
      span
        = product.likes_count
- else
  i class='fal fa-heart'
    span
      = product.likes_count

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'like', local: {product: @product, likes: @likes, like: @like})%>")

app/views/likes/delete.js.erb
$("#like-button").html("<%= j(render partial: 'like', local: {product: @product, likes: @likes, like: @like})%>")

app/views/products/_form.html.slim
= form_with model: product , local: true do |f|
  .form-group
    = f.file_field :image,accept: "image/png, image/jpeg, image/gif", direct_upload: true, id:'product_image'
    / - if product.image.attached?
    /   .image-box.my-3
    /     = image_tag product.image.variant(resize: "150x150"),multiple: true
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id:'product_name'
  .form-group
    = f.label :description
    = f.text_area :description,rows:5, class: 'form-control',id: 'product_description'
  = f.submit "投稿する", class:'btn btn-primary'

app/views/products/edit.html.slim
h1 編集ページ

.nav.justify-content-end
  = link_to '一覧',product_path,class:'nav-link'

= render partial: 'form',locals:{product: @product}

app/views/products/index.html.slim
h1.mb-3 投稿一覧


.container-fluid
  .row.show-grid
    - @products.each do |product|
      .col-sm-2.image-box
        = image_tag product.image.variant(resize: "150x150"),id: :image_prev if product.image.attached?
      .col-sm-10
        table.table.table-hover
          thead.thead-default
            tr
              th タイトル
              th いいね数
              th ユーザー
              th= Product.human_attribute_name(:created_at)
              th
          tbody
              tr
                td= link_to product.name, product
                td= product.likes_count
                td= product.user.nickname
                td= product.created_at.strftime('%y-%m-%d %h:%m')
                - if current_user == product.user
                  td
                    = link_to '編集',edit_product_path(product),class: 'btn btn-info mr-3'
                    = link_to '削除',product,method: :delete,data: {confirm: "「#{product.name}」を削除しますか？？"},class: 'btn btn-danger mr-3'

app/views/products/new.html.slim
h1 新規投稿
.nav.justify-content-end
  = link_to '一覧',products_path,class:'nav-link'

= render partial: 'form',locals:{product: @product}

app/views/products/show.html.slim
h1 詳細ページ

.nav.justify-content-end
  = link_to '投稿一覧に戻る', products_path, class: 'nav-link'
.image-box.mb-3
  = image_tag @product.image.variant(resize: "150x150",),id: :image_prev if @product.image.attached?
table.table.table-hover
  tbody
    tr
      th ユーザー
      td= @product.user.nickname
    tr
      th= Product.human_attribute_name(:created_at)
      td= @product.created_at.strftime('%y-%m-%d %h:%m')
    tr
      th いいねしたユーザー
      td
        -@product.iine_users.each do |user|
          =user.nickname
    tr
      th= Product.human_attribute_name(:description)
      td= simple_format(@product.description)
.content
  - if current_user != @product.user
    - if Like.find_by(user_id: @current_user.id, product_id: @product.id)
      .like-content.btn.btn-warning.mr-3
        = link_to product_like_path(@product.id),method: :delete do
          span class='fa fa-heart like-btn-unlike'
        span.like-btn-unlike
          = @product.likes_count
    - else
      .like-content.btn.btn-secondary.mr-3
        = link_to product_likes_path(@product.id), method: :post do
          span class='fa fa-heart like-btn'
        = @product.likes_count
  - if current_user == @product.user
      = link_to '編集',edit_product_path,class:'btn btn-info mr-3'
      = link_to '削除',product_path,method: :delete,data: {confirm: "「#{@product.name}」を削除しますか？？"},class: 'btn btn-danger mr-3'

app/views/users/index.html.slim
h1 ユーザー一覧
= @users.each do |user|
  = user.nickname
  = user.email
  hr
= link_to 'ホームへ戻る', root_path

app/views/users/show.html.slim
.contents
  h1
      = @nickname
      'さんのマイページ 
      .mb-3
  .nav.justify-content-end
    = link_to '投稿一覧に戻る', products_path, class: 'nav-link'
table.table.table-hover
  thead.thead-default
    tr
      th
      th= Product.human_attribute_name(:description)
      th= Product.human_attribute_name(:created_at)
      th
  tbody
    - @products.each do |product|
      tr
        td= image_tag product.image.variant(resize: "150x150",),id: :image_prev if product.image.attached?
        td= simple_format(product.description)
        td= product.created_at.strftime('%y-%m-%d %h:%m')
        td
          = link_to '編集',edit_product_path(product),class: 'btn btn-info mr-3'
          = link_to '削除',product,method: :delete,data: {confirm: "「#{product.name}」を削除しますか？？"},class: 'btn btn-danger mr-3'